-- Ejecutar en Supabase SQL Editor
-- Módulo Forecast: seguimiento previo a cotización/protocolo.

CREATE EXTENSION IF NOT EXISTS pgcrypto;

CREATE TABLE IF NOT EXISTS forecasts (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  numero BIGINT GENERATED BY DEFAULT AS IDENTITY UNIQUE,
  cliente_id UUID NULL REFERENCES clientes(id) ON DELETE SET NULL,
  nombre_cliente TEXT,
  nombre_proyecto TEXT NOT NULL,
  descripcion TEXT,
  unidad_negocio TEXT,
  contacto_nombre TEXT,
  contacto_email TEXT,
  contacto_telefono TEXT,
  etapa_actual TEXT NOT NULL DEFAULT 'Brief',
  estado TEXT NOT NULL DEFAULT 'Activo',
  prioridad TEXT NOT NULL DEFAULT 'Media',
  brief_doc_url TEXT,
  brief_edit_url TEXT,
  cotizacion_id UUID NULL REFERENCES cotizaciones(id) ON DELETE SET NULL,
  protocolo_id UUID NULL REFERENCES protocolos(id) ON DELETE SET NULL,
  observaciones TEXT,
  fecha_limite_general DATE,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS forecast_documentos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  forecast_id UUID NOT NULL REFERENCES forecasts(id) ON DELETE CASCADE,
  etapa TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'Documento',
  nombre TEXT NOT NULL,
  archivo_url TEXT,
  edit_url TEXT,
  comentarios TEXT,
  created_by TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS forecast_hitos (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  forecast_id UUID NOT NULL REFERENCES forecasts(id) ON DELETE CASCADE,
  titulo TEXT NOT NULL,
  tipo TEXT NOT NULL DEFAULT 'Otro',
  estado TEXT NOT NULL DEFAULT 'Pendiente',
  fecha DATE,
  fecha_fin DATE,
  responsable TEXT,
  notas TEXT,
  orden INTEGER NOT NULL DEFAULT 0,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE IF NOT EXISTS forecast_chat_mensajes (
  id UUID PRIMARY KEY DEFAULT gen_random_uuid(),
  forecast_id UUID NOT NULL REFERENCES forecasts(id) ON DELETE CASCADE,
  mensaje TEXT NOT NULL,
  user_id UUID NULL,
  user_name TEXT,
  user_email TEXT,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE INDEX IF NOT EXISTS idx_forecasts_etapa_actual ON forecasts(etapa_actual);
CREATE INDEX IF NOT EXISTS idx_forecasts_cliente_id ON forecasts(cliente_id);
CREATE INDEX IF NOT EXISTS idx_forecasts_cotizacion_id ON forecasts(cotizacion_id);
CREATE INDEX IF NOT EXISTS idx_forecasts_protocolo_id ON forecasts(protocolo_id);
CREATE INDEX IF NOT EXISTS idx_forecast_documentos_forecast_id ON forecast_documentos(forecast_id);
CREATE INDEX IF NOT EXISTS idx_forecast_hitos_forecast_id ON forecast_hitos(forecast_id);
CREATE INDEX IF NOT EXISTS idx_forecast_chat_mensajes_forecast_id ON forecast_chat_mensajes(forecast_id);
CREATE INDEX IF NOT EXISTS idx_forecast_chat_mensajes_created_at ON forecast_chat_mensajes(created_at);

CREATE OR REPLACE FUNCTION set_forecasts_updated_at()
RETURNS TRIGGER AS $$
BEGIN
  NEW.updated_at = NOW();
  RETURN NEW;
END;
$$ LANGUAGE plpgsql;

DROP TRIGGER IF EXISTS trg_forecasts_updated_at ON forecasts;
CREATE TRIGGER trg_forecasts_updated_at
BEFORE UPDATE ON forecasts
FOR EACH ROW
EXECUTE FUNCTION set_forecasts_updated_at();

DROP TRIGGER IF EXISTS trg_forecast_hitos_updated_at ON forecast_hitos;
CREATE TRIGGER trg_forecast_hitos_updated_at
BEFORE UPDATE ON forecast_hitos
FOR EACH ROW
EXECUTE FUNCTION set_forecasts_updated_at();

COMMENT ON TABLE forecasts IS 'Seguimiento previo del proyecto desde brief hasta pasar a protocolo';
COMMENT ON TABLE forecast_documentos IS 'Archivos y enlaces asociados a las etapas del forecast';
COMMENT ON TABLE forecast_hitos IS 'Fechas clave, entregables y tareas del forecast';
COMMENT ON TABLE forecast_chat_mensajes IS 'Chat interno asociado a cada forecast';

ALTER TABLE forecasts ENABLE ROW LEVEL SECURITY;
ALTER TABLE forecast_documentos ENABLE ROW LEVEL SECURITY;
ALTER TABLE forecast_hitos ENABLE ROW LEVEL SECURITY;
ALTER TABLE forecast_chat_mensajes ENABLE ROW LEVEL SECURITY;

DROP POLICY IF EXISTS "Authenticated full access" ON forecasts;
CREATE POLICY "Authenticated full access" ON forecasts
FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated full access" ON forecast_documentos;
CREATE POLICY "Authenticated full access" ON forecast_documentos
FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated full access" ON forecast_hitos;
CREATE POLICY "Authenticated full access" ON forecast_hitos
FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);

DROP POLICY IF EXISTS "Authenticated full access" ON forecast_chat_mensajes;
CREATE POLICY "Authenticated full access" ON forecast_chat_mensajes
FOR ALL TO authenticated
USING (auth.uid() IS NOT NULL)
WITH CHECK (auth.uid() IS NOT NULL);
